# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dQSR2 <- function(SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pmki1, Pmki2, Pk, Mi1Index, Mi2Index, Mi1, Mi2, EE, Eta, inv_sigma_SR1, inv_sigma_SR2, inv_sigma_UV, nu_0, eta_0) {
    .Call(`_WECAN_dQSR2`, SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pmki1, Pmki2, Pk, Mi1Index, Mi2Index, Mi1, Mi2, EE, Eta, inv_sigma_SR1, inv_sigma_SR2, inv_sigma_UV, nu_0, eta_0)
}

QUVY <- function(SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pk, EE, Eta, sigma_SR1, sigma_SR2, sigma_UV, SR1, SR2, UV, nu_0, eta_0) {
    .Call(`_WECAN_QUVY`, SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pk, EE, Eta, sigma_SR1, sigma_SR2, sigma_UV, SR1, SR2, UV, nu_0, eta_0)
}

dQUVY <- function(SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pmki1, Pmki2, Pk, Mi1Index, Mi2Index, Mi1, Mi2, EE, Eta, inv_sigma_SR1, inv_sigma_SR2, inv_sigma_UV, nu_0, eta_0) {
    .Call(`_WECAN_dQUVY`, SS1, SS2, U, RR1, RR2, V, Y, Lambda, beta, phi, lam, WW, Pmk, Pmki1, Pmki2, Pk, Mi1Index, Mi2Index, Mi1, Mi2, EE, Eta, inv_sigma_SR1, inv_sigma_SR2, inv_sigma_UV, nu_0, eta_0)
}

computeELBO_wn <- function(SS1, RR1, beta, SR1, SR2, UV, U, V, Y, Eta, log_h_phi, A_eta, a_phi, pi_phi, Pr_w_eta, EE, Phi_SR1, Phi_SR2, Phi_UV, WW, a_0, Lambda, lam, A_0, B_0, Pmk, Pk, Pm0, Elog_t_k, E_t_0, lambda_a, alpha, PmklogPmk, alphaTld, x_0) {
    .Call(`_WECAN_computeELBO_wn`, SS1, RR1, beta, SR1, SR2, UV, U, V, Y, Eta, log_h_phi, A_eta, a_phi, pi_phi, Pr_w_eta, EE, Phi_SR1, Phi_SR2, Phi_UV, WW, a_0, Lambda, lam, A_0, B_0, Pmk, Pk, Pm0, Elog_t_k, E_t_0, lambda_a, alpha, PmklogPmk, alphaTld, x_0)
}

computeEta <- function(SS2, RR2, beta, U, V, EE, Lambda, K) {
    .Call(`_WECAN_computeEta`, SS2, RR2, beta, U, V, EE, Lambda, K)
}

computePmk_wn <- function(SS1, RR1, U, V, Y, EE, WW, Eta, A_eta, a_phi, Pr_w_eta, h_phi, lambda_a, Elog_t_k, E_t_0) {
    .Call(`_WECAN_computePmk_wn`, SS1, RR1, U, V, Y, EE, WW, Eta, A_eta, a_phi, Pr_w_eta, h_phi, lambda_a, Elog_t_k, E_t_0)
}

evalConditionalLik_w <- function(z, SS1, RR1, U, V, Y, Eta, WW, alph, phi, EE, Pmk) {
    .Call(`_WECAN_evalConditionalLik_w`, z, SS1, RR1, U, V, Y, Eta, WW, alph, phi, EE, Pmk)
}

evalMargLogLik_w <- function(SS1, RR1, U, V, Y, Eta, WW, alph, phi, EE, Pmk) {
    .Call(`_WECAN_evalMargLogLik_w`, SS1, RR1, U, V, Y, Eta, WW, alph, phi, EE, Pmk)
}

evalMargPost_w <- function(SS1, RR1, SR1, SR2, UV, U, V, Y, Eta, A_eta, a_phi, pi_phi, Pr_w_eta, log_h_phi, sigma_SR1, sigma_SR2, sigma_UV, alph, EE, upsilon_SR1, upsilon_SR2, upsilon_UV, Phi_SR1, Phi_SR2, Phi_UV, WW, a_0, Lambda, lam, A_0, B_0, Pmk) {
    .Call(`_WECAN_evalMargPost_w`, SS1, RR1, SR1, SR2, UV, U, V, Y, Eta, A_eta, a_phi, pi_phi, Pr_w_eta, log_h_phi, sigma_SR1, sigma_SR2, sigma_UV, alph, EE, upsilon_SR1, upsilon_SR2, upsilon_UV, Phi_SR1, Phi_SR2, Phi_UV, WW, a_0, Lambda, lam, A_0, B_0, Pmk)
}

getPmki <- function(Pmk, Mi1Index, Mi1) {
    .Call(`_WECAN_getPmki`, Pmk, Mi1Index, Mi1)
}

indexEdges <- function(EE, n) {
    .Call(`_WECAN_indexEdges`, EE, n)
}

mat_mult <- function(A, B) {
    .Call(`_WECAN_mat_mult`, A, B)
}

